In [1]:
!ls

Backup	  data2008	    data_merged.csv
data2005  Data_Clean.ipynb  Data_Merging.ipynb

In [2]:
import numpy as np
import pandas as pd
from scipy.io import arff
import os

In [3]:
filenames=os.listdir('data2005')
print(filenames)

['entry04.weka.allclass.arff', 'entry06.weka.allclass.arff', 'entry02.weka.allclass.arff', 'entry03.weka.allclass.arff', 'entry07.weka.allclass.arff', 'entry05.weka.allclass.arff', 'entry10.weka.allclass.arff', 'entry09.weka.allclass.arff', 'entry01.weka.allclass.arff', 'entry08.weka.allclass.arff']

In [4]:
data=arff.loadarff('data2005/entry01.weka.allclass.arff')
df=pd.DataFrame(data[0])

df.head()

,4,8,13,14,15,16,17,18,19,21,...,257,258,259,260,261,262,263,264,265,266
0,80.0,16945.0,0.000152,0.000683,0.002332,0.045501,0.006292,0.199639,0.007419,60.0,...,0.005,1.487655,1.570266,0.773541,0.003650,0.971797,0.002430,1.097594,0.001423,b'WWW'
1,80.0,16913.0,0.000161,0.000676,0.001589,0.045358,0.005105,0.199854,0.007504,60.0,...,0.005,1.487655,1.570269,0.773541,0.003656,0.971797,0.002439,1.097594,0.001431,b'WWW'
2,80.0,16917.0,0.000190,0.000322,0.001621,0.045383,0.005388,0.199375,0.007519,60.0,...,0.005,1.487655,1.570266,0.773541,0.003650,0.971797,0.002430,1.097594,0.001422,b'WWW'
3,80.0,17018.0,0.000156,0.000269,0.001586,0.045290,0.005118,0.199557,0.007501,60.0,...,0.005,1.487655,1.570270,0.773541,0.003656,0.971797,0.002440,1.097594,0.001431,b'WWW'
4,80.0,16926.0,0.000170,0.000312,0.002793,0.046520,0.010827,0.199397,0.007392,60.0,...,0.005,1.487655,1.570222,0.773541,0.003591,0.971797,0.002344,1.097594,0.001361,b'WWW'

In [5]:
data[1]

Dataset: filelist.weka.allclass.csv
	4's type is numeric
	8's type is numeric
	13's type is numeric
	14's type is numeric
	15's type is numeric
	16's type is numeric
	17's type is numeric
	18's type is numeric
	19's type is numeric
	21's type is numeric
	22's type is numeric
	23's type is numeric
	24's type is numeric
	25's type is numeric
	26's type is numeric
	27's type is numeric
	28's type is numeric
	29's type is numeric
	30's type is numeric
	31's type is numeric
	32's type is numeric
	33's type is numeric
	34's type is numeric
	35's type is numeric
	36's type is numeric
	37's type is numeric
	38's type is numeric
	39's type is numeric
	40's type is numeric
	41's type is numeric
	43's type is numeric
	44's type is numeric
	45's type is numeric
	46's type is numeric
	47's type is numeric
	48's type is numeric
	49's type is numeric
	50's type is numeric
	51's type is numeric
	52's type is numeric
	53's type is numeric
	54's type is numeric
	55's type is numeric
	56's type is numeric
	57's type is numeric
	58's type is numeric
	59's type is numeric
	60's type is numeric
	61's type is numeric
	62's type is numeric
	63's type is numeric
	64's type is numeric
	65's type is numeric
	66's type is numeric
	67's type is numeric
	68's type is numeric
	69's type is numeric
	70's type is numeric
	71's type is numeric
	72's type is numeric
	73's type is numeric
	74's type is numeric
	75's type is numeric
	76's type is numeric
	77's type is nominal, range is ('Y', 'N')
	78's type is nominal, range is ('Y', 'N')
	79's type is nominal, range is ('Y', 'N')
	80's type is nominal, range is ('Y', 'N')
	81's type is numeric
	82's type is numeric
	83's type is nominal, range is ('Y', 'N')
	84's type is nominal, range is ('Y', 'N')
	85's type is numeric
	86's type is numeric
	87's type is numeric
	88's type is numeric
	89's type is numeric
	90's type is numeric
	91's type is numeric
	92's type is numeric
	93's type is numeric
	94's type is numeric
	95's type is numeric
	96's type is numeric
	97's type is numeric
	98's type is numeric
	99's type is numeric
	100's type is numeric
	101's type is numeric
	102's type is numeric
	103's type is numeric
	104's type is numeric
	105's type is numeric
	106's type is numeric
	107's type is numeric
	108's type is numeric
	109's type is numeric
	110's type is numeric
	111's type is numeric
	112's type is numeric
	113's type is numeric
	114's type is numeric
	115's type is numeric
	116's type is numeric
	117's type is numeric
	118's type is numeric
	119's type is numeric
	120's type is numeric
	121's type is numeric
	122's type is numeric
	123's type is numeric
	124's type is numeric
	125's type is numeric
	126's type is numeric
	127's type is numeric
	128's type is numeric
	129's type is numeric
	130's type is numeric
	131's type is numeric
	132's type is numeric
	133's type is numeric
	134's type is numeric
	135's type is numeric
	136's type is numeric
	137's type is numeric
	138's type is numeric
	139's type is numeric
	140's type is numeric
	141's type is numeric
	142's type is numeric
	143's type is numeric
	144's type is numeric
	145's type is numeric
	146's type is numeric
	147's type is numeric
	148's type is numeric
	149's type is numeric
	150's type is numeric
	151's type is numeric
	152's type is numeric
	153's type is numeric
	154's type is numeric
	155's type is numeric
	156's type is numeric
	157's type is numeric
	158's type is numeric
	159's type is numeric
	160's type is numeric
	161's type is numeric
	162's type is numeric
	163's type is numeric
	164's type is numeric
	166's type is numeric
	167's type is numeric
	168's type is numeric
	169's type is numeric
	170's type is numeric
	171's type is numeric
	172's type is numeric
	173's type is numeric
	174's type is numeric
	175's type is numeric
	176's type is numeric
	177's type is numeric
	178's type is numeric
	179's type is numeric
	180's type is numeric
	181's type is numeric
	182's type is numeric
	183's type is numeric
	184's type is numeric
	185's type is numeric
	186's type is numeric
	188's type is numeric
	189's type is numeric
	190's type is numeric
	191's type is numeric
	192's type is numeric
	193's type is numeric
	194's type is numeric
	195's type is numeric
	196's type is numeric
	197's type is numeric
	198's type is numeric
	199's type is numeric
	200's type is numeric
	201's type is numeric
	202's type is numeric
	203's type is numeric
	204's type is numeric
	205's type is numeric
	206's type is numeric
	207's type is numeric
	208's type is numeric
	210's type is numeric
	211's type is numeric
	212's type is numeric
	213's type is numeric
	214's type is numeric
	215's type is numeric
	216's type is numeric
	218's type is numeric
	219's type is numeric
	220's type is numeric
	221's type is numeric
	222's type is numeric
	223's type is numeric
	224's type is numeric
	225's type is numeric
	227's type is numeric
	228's type is numeric
	229's type is numeric
	230's type is numeric
	231's type is numeric
	232's type is numeric
	233's type is numeric
	234's type is numeric
	235's type is numeric
	236's type is numeric
	237's type is numeric
	238's type is numeric
	239's type is numeric
	240's type is numeric
	241's type is numeric
	242's type is numeric
	243's type is numeric
	244's type is numeric
	245's type is numeric
	246's type is numeric
	247's type is numeric
	248's type is numeric
	249's type is numeric
	250's type is numeric
	251's type is numeric
	252's type is numeric
	253's type is numeric
	254's type is numeric
	255's type is numeric
	256's type is numeric
	257's type is numeric
	258's type is numeric
	259's type is numeric
	260's type is numeric
	261's type is numeric
	262's type is numeric
	263's type is numeric
	264's type is numeric
	265's type is numeric
	266's type is nominal, range is ('WWW', 'MAIL', 'FTP-CONTROL', 'FTP-PASV', 'ATTACK', 'P2P', 'DATABASE', 'FTP-DATA', 'MULTIMEDIA', 'SERVICES', 'INTERACTIVE', 'GAMES')

In [6]:
dfs=[]
for file in filenames:
    data=arff.loadarff('data2005/'+ file)
    dfs.append(pd.DataFrame(data[0]))
df=pd.concat(dfs,ignore_index=True)

In [7]:
df.head()

,4,8,13,14,15,16,17,18,19,21,...,257,258,259,260,261,262,263,264,265,266
0,80.0,51063.0,0.000134,0.000262,0.000439,0.046510,0.114171,0.153290,0.005142,66.0,...,0.005,1.487655,1.570576,0.773541,0.004160,0.971797,0.003283,1.097594,0.002344,b'WWW'
1,80.0,51094.0,0.000001,0.000173,0.000259,0.042580,0.082782,0.151153,0.004833,66.0,...,0.006,1.487655,1.570649,0.773541,0.005127,0.971797,0.004223,1.097594,0.003263,b'WWW'
2,80.0,51062.0,0.000001,0.000293,0.000517,0.046451,0.114882,0.149624,0.005026,66.0,...,0.005,1.487655,1.570568,0.773541,0.004144,0.971797,0.003254,1.097594,0.002305,b'WWW'
3,80.0,51089.0,0.000015,0.000326,0.000524,0.046915,0.116692,0.148243,0.004917,66.0,...,0.005,1.487655,1.570552,0.773541,0.004109,0.971797,0.003189,1.097594,0.002220,b'WWW'
4,80.0,51057.0,0.000077,0.000175,0.000349,0.042728,0.085012,0.149947,0.004664,66.0,...,0.005,1.487655,1.570552,0.773541,0.004110,0.971797,0.003191,1.097594,0.002222,b'WWW'

In [8]:
df.shape

(377526, 249)

In [9]:
df.to_csv('data_merged.csv',index=False)

In [10]:
!ls

Backup	  data2008	    data_merged.csv
data2005  Data_Clean.ipynb  Data_Merging.ipynb